### PR TITLE
Include Exhibitor::Util in the proper Chef Scope

### PR DESCRIPTION
**Pull request by tylermarshall**
When the `service_conf` hash was moved from Chef Resources to the Chef Recipe scope in this change https://github.com/evertrue/exhibitor-cookbook/commit/b999b200b7f859de6dc60ab451c15eebb580b8ea the library was not included in the proper scope. As a result the following error is present:

```
NoMethodError
-------------
No resource or method named `format_cli_options' for `Chef::Recipe "service"'
```

By including the library in the `Chef::Recipe` scope the error is no longer present. If you could please take a look @jeffbyrnes and let me know if there is some oversight I missed.

### CODE REVIEW

**Comment by jeffbyrnes** [comment]
@tylermarshall I’m not able to reproduce this error. Would you detail exactly how you’re running into it?

**Comment by jeffbyrnes** [comment]
@tylermarshall I’ve added automated testing using Travis, which you can take advantage of if you rebase against master.

**Comment by tylermarshall** [comment]
@jeffbyrnes , sorry for the delay. To reproduce this error you need to set the attribute `default['exhibitor']['install_method'] = 'download'`, which will not run the `_exhibitor_build` recipe. Therefore, when the run_list is flattened it only runs the `default` and `service`, which includes the util library only in the `Chef::Resource` scope.

By having the `_exhibitor_build` recipe run it includes the library into the proper scope (https://github.com/evertrue/exhibitor-cookbook/blob/master/recipes/_exhibitor_build.rb#L17-L19), therefore the `service` recipe does not have that error. But all of the library calls within the `service` recipe are made in the `Chef::Recipe` scope since version 0.10.0.

I've added the test case for runit as well as testing the `download` install method for exhibitor. Let me know if anything is unclear.

**Comment by jeffbyrnes** [comment]
@tylermarshall ahhh, gotcha. Seems we have a hole in the test cases; thanks for supplying a new one!

**Comment by tylermarshall** [comment]
@jeffbyrnes it looks like some of your Travis settings are off. I'm not sure how I should go about resolving the CI issue, but happy to lend a hand where I can.

**Comment by jeffbyrnes** [comment]
@tylermarshall dang, I thought this might happen. I think I might have to shift around how the encrypted settings are stored.

**Comment by arnaud036** [comment]
@jeffbyrnes Also getting hit by this issue

**Comment by jeffbyrnes** [comment]
Sorry folks, haven’t had time to come back to this. Trying!

**Comment by jeffbyrnes** [comment]
I’ve merged this in, updated the Travis tests to also pursue the `runit` suite added by @tylermarshall, and, if those tests pass, I’ll cut a new release & push that to Supermarket.

Sorry again for the slowness, and thanks for your patience!

**Comment by arnaud036** [comment]
Thanks @jeffbyrnes for your work on this cookbook. Very helpful.

**Comment by jeffbyrnes** [comment]
@tylermarshall @arnaud036 well, this solves the recipe compiling & running, but it would seem that Exhibitor itself now does not want to start as a downloaded artifact from the mirror URL supplied:

```bash
vagrant@download-ubuntu-1404:~$ sudo su zookeeper -c '/usr/lib/jvm/java-6-openjdk-amd64/bin/java -Dlog4j.configuration=file:///opt/exhibitor/log4j.properties -jar /opt/exhibitor/1.5.5.jar --configtype file --defaultconfig /opt/exhibitor/exhibitor.properties --fsconfigdir /tmp --fsconfigname exhibitor.properties --hostname 10.0.2.15 --port 8080'
Exception in thread "main" java.lang.NullPointerException
	at sun.launcher.LauncherHelper.getMainClassFromJar(LauncherHelper.java:353)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:402)
```

I got some better results when I installed Java 7:

```bash
vagrant@download-ubuntu-1404:~$ sudo su zookeeper -c '/usr/lib/jvm/java-7-openjdk-amd64/bin/java -Dlog4j.configuration=file:///opt/exhibitor/log4j.properties  -jar /opt/exhibitor/1.5.5.jar --configtype file --defaultconfig /opt/exhibitor/exhibitor.properties --fsconfigdir /tmp --fsconfigname exhibitor.properties --hostname 10.0.2.15 --port 8080'
no main manifest attribute, in /opt/exhibitor/1.5.5.jar
```

which lead me to Netflix/exhibitor#284, and now we know that download link doesn’t work as-is.

I’ll open a new issue to cover this, since it’s separate from the issue described here (which has been solved).

**Comment by tylermarshall** [comment]
@jeffbyrnes That's interesting information. As you mentioned, that was outside the scope of what I was trying to fix. I noticed the test cases were missing  for runit and added them. However, during my testing I wasn't even able to get exhibitor to start correctly via runit even without the download link. 

Rather than tweak the other suite I added the download link to the runit suite to navigate the same recipe pattern that reveals the compile issue.

**Comment by jeffbyrnes** [comment]
@tylermarshall as it turns out the default suite uses runit, so that was already covered; there are only two service type (`runit`, the default, and `upstart`), so things were already covered there.

Not sure why you had trouble starting Exhibitor using that method, with Gradle assembling it, honestly.

As it stands, I’m now in the midst of some heavy refactoring in #37 to clean this all up.

**Comment by jeffbyrnes** [comment]
@tylermarshall @arnaud036 `exhibitor ~> 2.0` should solve your woes in a meaningful way, though it does _not_ offer a download option at this time.

If you feel that’s a must-have, please open an issue, and I’ll add a third `install_option`, `download`, that clearly calls out that you must supply your _own_ pre-built copy of the Exhibitor JAR.

**Pull request merged**
