### PR TITLE
Refactor to correctly offer install methods

### LINKED ISSUE #37: Correctly install Exhibitor via download method
As discovered while testing #34, using `node['exhibitor']['install_method'] = 'download'` does not work properly, as the standalone JAR is a library JAR, not a runnable one (see Netflix/exhibitor#284 for details).

### PR DESCRIPTION
**Pull request by jeffbyrnes**
Fixes #37, relates to #34.

This introduces some breaking changes to the cookbook, primarily around the install_method attributes.

Consider it a precursor to the breaking changes eventually coming with #36.

@tylermarshall, would love your 👀 on this.

### CODE REVIEW

**Comment by jeffbyrnes** [comment]
Green build wooooo!

**Comment by tylermarshall** [comment]
@jeffbyrnes , sorry for the delay. It's been a crazy week. I'll still take a look at these changes before the week's over.

**Comment by tylermarshall** [comment]
@jeffbyrnes I finally had the time to review these changes and they all check out. I appreciate the work on this and it resolves all my issues. If anything comes up I'll be sure to put in another PR to resolve my issues.

**Comment by jeffbyrnes** [comment]
@tylermarshall glad to hear it! Enjoy v2.0.0 of the cookbook, with all of these changes baked in.

**Pull request merged**
